### ISSUE TITLE
.

### ISSUE THREAD

**Issue by umutfahriozkan** [thearkxd/discord-advanced-stat-bot#3]
.

**Comment by thearkxd** [comment]
Fark etmeme değil, bu bilerek yaptığım bir şey ve ayrıca sırf bunun için farklı bir modül kullanmaya ihtiyaç duymuyorum. Zaten voiceStateUpdate eventinde belli başlı kontroller ile kişinin kanala girdiğini mi, çıktığını mı, yoksa başka bir işlem mi yaptığını algılatabilirsiniz :)

**Comment by thearkxd** [comment]
Size de kullanmamanızı tavsiye ederim.
